version: '3'
services:
    memcached:
        image: memcached
        restart: always

    mongodb:
        image: library/mongo:3.4.9
        volumes:
           - ./data/mongodb:/data/db
           - /etc/localtime:/etc/localtime:ro
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
        ports:
           - "27017:27017"
        restart: always
        privileged: true

    web:
        image: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/nginx/ssl"
            - "./web:/var/app"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "80:80"
            - "443:443"
            - "81:81"
            - "444:444"
            - "82:82"
            - "445:445"
            - "83:83"
            - "446:446"
            - "84:84"
            - "447:447"
            - "85:85"
            - "449:449"
            - "86:86"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - cloudschool
            - cloudschool_admin
            - mysqldb
            - admin_mysqldb
            - mongodb
#            - cms_mysqldb
#            - sfs3
#            - community_college
#        networks:
#              default:
#                ipv4_address: 172.18.0.111
    cloudschool:
        image: hamichen/php-fpm-7.3.11
        restart: always
        volumes:
            - "./web:/var/app"
            - "/etc/localtime:/etc/localtime:ro"
        working_dir: /var/app/cloudschool

    cloudschool_admin:
         image: hamichen/php-fpm-7.3.11
         restart: always
         volumes:
            - "./web:/var/app"
            - "/etc/localtime:/etc/localtime:ro"
         working_dir: /var/app/cloudschool_admin

    cloudschool_boeapi:
         image: hamichen/php-fpm-7.3.11
         restart: always
         volumes:
            - "./web:/var/app"
            - "/etc/localtime:/etc/localtime:ro"
         working_dir: /var/app/cloudschool_boeapi

    cloudschool_api:
         image: hamichen/php-fpm-7.3.11
         restart: always
         volumes:
            - "./web:/var/app"
            - "/etc/localtime:/etc/localtime:ro"
         working_dir: /var/app/cloudschool_api


    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=${MYSQL_HOST}
            - PMA_HOSTS=mysqldb,admin_mysqldb,cms_mysqldb
        restart: always
        depends_on:
            - mysqldb
            - admin_mysqldb

    mysqldb:
        image: mariadb:10.3
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - /etc/localtime:/etc/localtime:ro

        command: mysqld --sql_mode=""

    admin_mysqldb:
            image: mariadb:10.3
            restart: always
            env_file:
                - ".env"
            environment:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            ports:
                - "3306"
            volumes:
                - "./data/db/admin_mysql:/var/lib/mysql"
                - /etc/localtime:/etc/localtime:ro

            command: mysqld --sql_mode=""

#networks:
#  default:
#    external:
#      name: mynet
